Weights:
  Pi3: './weights/model.safetensors'
  DBoW: './weights/ORBvoc.txt'
  SALAD: './weights/dino_salad.ckpt'
  DNIO: './weights/dinov2_vitb14_pretrain.pth'

Model:
  chunk_size: 60
  overlap: 30
  loop_chunk_size: 20 # imgs of loop chunk = 2 * loop_chunk_size
  loop_enable: True
  useDBoW: False
  delete_temp_files: True
  temp_files_location: 'disk' # choose between 'disk' or 'cpu_memory'
  align_lib: 'triton' # choose among 'triton' (GPU), 'torch' (GPU), 'numba' (CPU) or 'numpy' (CPU)
  align_method: 'sim3' # choose among 'sim3', 'se3' or 'scale+se3'
  scale_compute_method: 'auto' # choose among 'auto', 'ransac' or 'weighted'. It is used when align_method == 'scale+se3'
  # 'scale+se3' is computed using depth, where Pi3 cannot privide depth output. So 'scale+se3' are not available for Pi-Long
  align_type: 'dense' # choose between 'dense' or 'sparse'. Sparse align is constructing, not avaible for now
  
  IRLS:
    delta: 0.1
    max_iters: 5
    tol: 1e-9

  Pointcloud_Save:
    sample_ratio: 0.015
    conf_threshold_coef: 0.75 # conf_threshold = np.mean(confs) * conf_threshold_coef

Loop:
  DBoW:
    thresh: 0.034
    num_repeat: 3
    NMS: 25

  SALAD:
    image_size: [336, 336]
    batch_size: 32
    similarity_threshold: 0.7
    top_k: 5
    use_nms: True
    nms_threshold: 25

  SIM3_Optimizer:
    lang_version: 'cpp' 
    # choose between 'cpp' or 'python'. will auto set 'python' if c++ version has not installed
    max_iterations: 30
    lambda_init: 1e-6